### ISSUE TITLE
Module compiled with Swift 4.1 cannot be imported by the Swift 4.2.1 compiler

### ISSUE THREAD

**Issue by Bala-Nair-Bose** [navisens/iOS-SDK#3]
I'm having the framework cannot be imported issue due to Swift compiler version.  My setup is:
- OSX Mojave
- Xcode 10.1 Build version 10B61

I'm trying to build the beertest sample app for the first time.  Do you have a version built for 4.2.1 or can you build me a version which I can download and reference locally in my Podfile?  Thanks

**Comment by jamesgrantham** [comment]
Swift plugin modules have been recompiled for 4.2
